runtime: python
runtime_config:
        python_version: 3
env: flex
automatic_scaling:
    min_num_instances: 1
    max_num_instances: 2
entrypoint: streamlit run --server.enableCORS false app.py --server.port 8080