runtime: custom
env: flex
# resources:
#   cpu: 1
#   memory_gb: 2
#   disk_size_gb: 10
# skip_files:
#   - env/
#   - .git/
#   - Dockerfile
#   - Procfile
#   - Procfile.windows
#   - README.md
#   - runtime.txt
#   - setup.py
#   - create_config.sh
entrypoint: streamlit run --server.enableCORS false app.py --server.port 8080